spring.application.name=blog

spring.jpa.database=mysql
spring.datasource.url=jdbc:mysql://localhost:3306/laravel
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update